name: 'Terraform Deploy using GitHub Secrets'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'azure-infra/environments/prod/**'
      - '.github/workflows/azure_apply.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: azure-infra/environments/prod
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Use GitHub Secrets to set subscription ID
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}  # Use GitHub Secrets to set tenant ID
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}  # Use GitHub Secrets to set client ID
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: azure-infra/environments/prod
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: azure-infra/environments/prod
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Use GitHub Secrets to set subscription ID
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}  # Use GitHub Secrets to set tenant ID
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}  # Use GitHub Secrets to set client ID
        run: terraform plan -var-file=azure.tfvars -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: azure-infra/environments/prod
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Use GitHub Secrets to set subscription ID
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}  # Use GitHub Secrets to set tenant ID
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}  # Use GitHub Secrets to set client ID
        run: terraform apply -var-file=azure.tfvars -auto-approve -input=false
