name: 'Terraform Deploy using OIDC and Key Vault Secrets'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'azure-infra/environments/prod/**'
      - '.github/workflows/azure_apply.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Retrieve secrets from Azure Key Vault
        run: |
          AZURE_SUBSCRIPTION_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-subscription-id --query value -o tsv)
          AZURE_TENANT_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-tenant-id --query value -o tsv)
          AZURE_CLIENT_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-client-id --query value -o tsv)

          echo "AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${AZURE_TENANT_ID}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${AZURE_CLIENT_ID}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: azure-infra/environments/prod
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: azure-infra/environments/prod
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: azure-infra/environments/prod
        env:
          TF_VAR_azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
          TF_VAR_azure_client_id: ${{ env.AZURE_CLIENT_ID }}
        run: terraform plan -var-file=azure.tfvars -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: azure-infra/environments/prod
        env:
          TF_VAR_azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
          TF_VAR_azure_client_id: ${{ env.AZURE_CLIENT_ID }}
        run: terraform apply -var-file=azure.tfvars -auto-approve -input=false
