name: Azure Infra Provision

on:
  push:
    branches: [ "main" ]
    paths:
      - 'azure-infra/environments/prod/**'
      - '.github/workflows/azure_apply.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Login to Azure with OIDC'
      uses: azure/login@v1
      with:
        client-id: d385aa71-0f89-4204-964c-2cbb4322fcc0
        tenant-id: 4c470cc0-914e-41d8-b3f2-2812cb01d186
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Run Terraform Init from the correct directory
    - name: 'Terraform Init'
      run: terraform init
      working-directory: azure-infra/environments/prod

    # Run Terraform Plan from the correct directory
    - name: 'Terraform Plan'
      run: terraform plan
      working-directory: azure-infra/environments/prod

    # Run Terraform Apply from the correct directory
    - name: 'Terraform Apply'
      run: terraform apply -auto-approve
      working-directory: azure-infra/environments/prod
