name: Azure Infra Provision

on:
  push:
    branches: [ "main" ]
    paths:
      - 'azure-infra/environments/prod/**'
      - '.github/workflows/azure_apply.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Login to Azure with OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Pass necessary environment variables to Terraform for Service Principal authentication
    - name: 'Terraform Init'
      run: terraform init
      working-directory: azure-infra/environments/prod
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Terraform Plan'
      run: terraform plan
      working-directory: azure-infra/environments/prod
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve
      working-directory: azure-infra/environments/prod
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
