jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Retrieve secrets from Azure Key Vault
        run: |
          AZURE_SUBSCRIPTION_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-subscription-id --query value -o tsv)
          AZURE_TENANT_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-tenant-id --query value -o tsv)
          AZURE_CLIENT_ID=$(az keyvault secret show --vault-name aitdevops-vault --name azure-client-id --query value -o tsv)

          echo "AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${AZURE_TENANT_ID}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${AZURE_CLIENT_ID}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: azure-infra/environments/prod
        env:
          ARM_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        run: terraform init -input=false
