name: Test GCP Connection

on:
  workflow_dispatch:

jobs:
  test-gcp-connection:
    name: Test GCP Connection
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to GCP using Workload Identity Federation
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
        service_account: "github-actions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com"

    - name: List Google Cloud Storage Buckets
      run: gsutil ls
      shell: bash

    - name: Create a Test Storage Bucket
      run: |
        gsutil mb -l us-central1 gs://test-bucket-${{ secrets.PROJECT_ID }}-$(date +%s)/
      shell: bash

    - name: Output Completion Message
      run: echo "Test GCP operations completed successfully."
