name: Test GCP Connection

on:
  workflow_dispatch: 

permissions:
  contents: read
  id-token: write

jobs:
  test-gcp:
    name: 'Test GCP Connection'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'bucket-prd@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Create a Test Storage Bucket
      run: |
        gsutil mb -l us-central1 gs://test-bucket-${{ secrets.PROJECT_ID }}-$(date +%s)/
      shell: bash

    - name: List Google Cloud Storage Buckets
      run: gsutil ls
      shell: bash
