name: Create GCS Bucket

on:
  workflow_dispatch: 

permissions:
  contents: read
  id-token: write

jobs:
  create-bucket:
    name: Create GCS Bucket
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate to Google Cloud using Workload Identity Federation
    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/664946097791/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'github-actions@devops-projects-426703.iam.gserviceaccount.com'

    # Set up Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Create a new Google Cloud Storage bucket
    - name: Create GCS Bucket
      run: |
        BUCKET_NAME="my-new-gcs-bucket-$(date +%s)"
        gsutil mb -l us-central1 gs://$BUCKET_NAME/
        echo "Created bucket: $BUCKET_NAME"

    # List all Google Cloud Storage buckets to verify creation
    - name: List GCS Buckets
      run: gsutil ls
