name: Build aitdevops

# Trigger the workflow manually via GitHub UI
on:
  workflow_dispatch:

jobs:
  terraform:
    name: Provision aitdevops Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Replace with your desired Terraform version

    - name: Initialize Terraform
      working-directory: ./gcp-infra/environments/prod
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ./gcp-infra/environments/prod
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./gcp-infra/environments/prod
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: terraform apply -auto-approve

    - name: Output Completion Message
      run: echo "Infrastructure for aitdevops has been successfully provisioned."
