permissions:
  id-token: write
  contents: read

steps:
- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v1
  with:
    workload_identity_provider: projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/aitdevops-pool/providers/aitdevops-pool
    service_account: aitdevops-tf-apply@${PROJECT_ID}.iam.gserviceaccount.com

- name: Terraform Apply
  run: terraform apply -auto-approve
